name: UdacityAzureML
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pandas=0.25.3
  - pip=20.1.1
  - py-xgboost=0.90
  - python=3.6.9
  - scipy=1.5.2
  - pandas
  - pip:
    - numpy==1.19.3
    - azureml-accel-models==1.19.0
    - azureml-automl-core==1.19.0
    - azureml-automl-runtime==1.19.0
    - azureml-core==1.19.0
    - azureml-datadrift==1.19.0
    - azureml-dataprep==2.6.1
    - azureml-dataprep-native==26.0.0
    - azureml-dataprep-rslex==1.4.0
    - azureml-dataset-runtime==1.19.0.post1
    - azureml-defaults==1.19.0
    - azureml-explain-model==1.19.0
    - azureml-interpret==1.19.0
    - azureml-mlflow==1.19.0
    - azureml-model-management-sdk==1.0.1b6.post1
    - azureml-opendatasets==1.19.0
    - azureml-pipeline==1.19.0
    - azureml-pipeline-core==1.19.0
    - azureml-pipeline-steps==1.19.0
    - azureml-sdk==1.19.0
    - azureml-telemetry==1.19.0
    - azureml-train==1.19.0
    - azureml-train-automl==1.19.0
    - azureml-train-automl-client==1.19.0
    - azureml-train-automl-runtime==1.19.0
    - azureml-train-core==1.19.0
    - azureml-train-restclients-hyperdrive==1.19.0
    - azureml-widgets==1.19.0
    - ipywidgets==7.5.1
    - matplotlib
    - notebook==6.1.5
    - pyarrow==1.0.1
    - requests
    - scikit-image
    - scikit-learn==0.22.2.post1
